# Generated by Django 5.1.2 on 2026-01-01 16:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('calories', models.DecimalField(decimal_places=2, max_digits=7)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=6)),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fats', models.DecimalField(decimal_places=2, max_digits=6)),
                ('high_in_vitamin_d', models.BooleanField(default=False)),
                ('high_in_vitamin_b12', models.BooleanField(default=False)),
                ('high_in_iron', models.BooleanField(default=False)),
                ('high_in_calcium', models.BooleanField(default=False)),
                ('high_in_omega3', models.BooleanField(default=False)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['meal_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NutritionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('calories', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('protein', models.DecimalField(decimal_places=2, default=0, help_text='Grams', max_digits=6)),
                ('carbohydrates', models.DecimalField(decimal_places=2, default=0, help_text='Grams', max_digits=6)),
                ('fats', models.DecimalField(decimal_places=2, default=0, help_text='Grams', max_digits=6)),
                ('vitamin_d', models.DecimalField(decimal_places=2, default=0, help_text='Micrograms (mcg)', max_digits=6)),
                ('vitamin_b12', models.DecimalField(decimal_places=2, default=0, help_text='Micrograms (mcg)', max_digits=6)),
                ('iron', models.DecimalField(decimal_places=2, default=0, help_text='Milligrams (mg)', max_digits=6)),
                ('calcium', models.DecimalField(decimal_places=2, default=0, help_text='Milligrams (mg)', max_digits=6)),
                ('omega3', models.DecimalField(decimal_places=2, default=0, help_text='Grams', max_digits=6)),
                ('barcode', models.CharField(blank=True, help_text='Product barcode (UPC/EAN)', max_length=50, null=True)),
                ('serving_size', models.CharField(blank=True, help_text="e.g., '1 cup', '100g'", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nutrition_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_entries', to='nutrition.nutritionlog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
