# Generated by Django 5.1.2 on 2026-01-01 16:15

from django.db import migrations

def populate_meal_suggestions(apps, schema_editor):
    MealSuggestion = apps.get_model('nutrition', 'MealSuggestion')
    
    suggestions = [
        {
            'name': 'Grilled Salmon with Spinach',
            'description': 'Rich in Omega-3 fatty acids and iron. Perfect for heart health and energy.',
            'calories': 350,
            'protein': 30,
            'carbohydrates': 10,
            'fats': 20,
            'high_in_omega3': True,
            'high_in_iron': True,
            'high_in_vitamin_d': True,
            'meal_type': 'lunch',
        },
        {
            'name': 'Fortified Cereal with Milk',
            'description': 'Vitamin D and calcium-rich breakfast for strong bones.',
            'calories': 250,
            'protein': 10,
            'carbohydrates': 40,
            'fats': 5,
            'high_in_vitamin_d': True,
            'high_in_calcium': True,
            'high_in_vitamin_b12': True,
            'meal_type': 'breakfast',
        },
        {
            'name': 'Beef and Kale Stir-Fry',
            'description': 'High in iron and B12. Great for preventing anemia.',
            'calories': 400,
            'protein': 35,
            'carbohydrates': 25,
            'fats': 18,
            'high_in_iron': True,
            'high_in_vitamin_b12': True,
            'meal_type': 'dinner',
        },
        {
            'name': 'Greek Yogurt with Almonds',
            'description': 'Calcium and protein-rich snack.',
            'calories': 200,
            'protein': 15,
            'carbohydrates': 20,
            'fats': 8,
            'high_in_calcium': True,
            'high_in_vitamin_b12': True,
            'meal_type': 'snack',
        },
        {
            'name': 'Chia Seed Pudding',
            'description': 'Excellent source of Omega-3 and fiber.',
            'calories': 180,
            'protein': 6,
            'carbohydrates': 25,
            'fats': 9,
            'high_in_omega3': True,
            'high_in_calcium': True,
            'meal_type': 'snack',
        },
        {
            'name': 'Mushroom Omelette',
            'description': 'Vitamin D from mushrooms and eggs. Perfect protein breakfast.',
            'calories': 280,
            'protein': 20,
            'carbohydrates': 8,
            'fats': 18,
            'high_in_vitamin_d': True,
            'high_in_vitamin_b12': True,
            'meal_type': 'breakfast',
        },
        {
            'name': 'Sardines on Whole Grain Toast',
            'description': 'Omega-3, calcium, and vitamin D powerhouse.',
            'calories': 320,
            'protein': 22,
            'carbohydrates': 28,
            'fats': 14,
            'high_in_omega3': True,
            'high_in_calcium': True,
            'high_in_vitamin_d': True,
            'meal_type': 'lunch',
        },
        {
            'name': 'Lentil and Spinach Curry',
            'description': 'Plant-based iron and protein.',
            'calories': 300,
            'protein': 18,
            'carbohydrates': 45,
            'fats': 6,
            'high_in_iron': True,
            'meal_type': 'dinner',
        },
    ]
    
    for suggestion_data in suggestions:
        MealSuggestion.objects.create(**suggestion_data)

def reverse_populate(apps, schema_editor):
    MealSuggestion = apps.get_model('nutrition', 'MealSuggestion')
    MealSuggestion.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_meal_suggestions, reverse_populate),
    ]
